FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
RUN echo '<h1 style="font-family: Arial, sans-serif; color: #2c3e50; text-align: center;">Hi, I am from App2</h1>' > /usr/share/nginx/html/index.html
